### ISSUE TITLE
(URGENT) file paths in `schemas.yaml` wrong

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#100]
Method to reproduce:

1. Clone https://github.com/metanorma/iso-10303-srl into a local directory
2. Enter `iso-10303-srl` and run `wget https://github.com/metanorma/stepmod2mn/releases/download/v1.24/stepmod2mn-1.24.jar`
3. Locate the iso-10303-stepmod-wg12 repository locally.

Run this command:
https://github.com/metanorma/iso-10303-stepmod-annotate/blob/a384cede6b3f127d473659a2fc53a1aa346cab58/.github/workflows/migrate.yml#L37-L41

```sh
bundle exec stepmod-srl-migrate \
            --stepmod2mn-executeable stepmod2mn-1.24.jar \
            --srl-schemas-dir schemas \
            --srl-docs-dir docs \
            --stepmod-data-dir iso-10303-stepmod-wg12
```

Now do this:

```
bundle
cd docs/resources/geometric_and_topological_representation
bundle exec metanorma document.adoc
```

Notice that the file paths in `docs/resources/geometric_and_topological_representation/schemas.yaml` are wrong:
* They should be using the post-migration file paths
* They should not have `_annotated.exp` endings

Original:
```yaml
---
schemas:
  geometry_schema:
    path: ../../../../iso-10303-stepmod-wg12/data/resources/geometry_schema/geometry_schema_annotated.exp
  topology_schema:
    path: ../../../../iso-10303-stepmod-wg12/data/resources/topology_schema/topology_schema_annotated.exp
  geometric_model_schema:
    path: ../../../../iso-10303-stepmod-wg12/data/resources/geometric_model_schema/geometric_model_schema_annotated.exp
  scan_data_3d_shape_model_schema:
    path: ../../../../iso-10303-stepmod-wg12/data/resources/scan_data_3d_shape_model_schema/scan_data_3d_shape_model_schema_annotated.exp
```

Should be:
```yaml
---
schemas:
  geometry_schema:
    path: ../../../schemas/geometry_schema/geometry_schema.exp
  topology_schema:
    path: ../../../schemas/topology_schema/topology_schema.exp
  geometric_model_schema:
    path: ../../../schemas/geometric_model_schema/geometric_model_schema.exp
  scan_data_3d_shape_model_schema:
    path: ../../../schemas/scan_data_3d_shape_model_schema/scan_data_3d_shape_model_schema.exp
```
