### ISSUE TITLE
Generated `{srl-documents-path}/metanorma.yml` file contains duplicated entries (also better to sort by number)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#112]
This occurs in stepmod2mn v1.26.

```yaml
---
metanorma:
  source:
    files:
      - iso-10303-61/document.adoc
      - iso-10303-41/document.adoc
      - iso-10303-518/document.adoc
      - iso-10303-51/document.adoc
      - iso-10303-101/document.adoc
      - iso-10303-45/document.adoc
      - iso-10303-503/document.adoc
      - iso-10303-521/document.adoc
      - iso-10303-520/document.adoc
      - iso-10303-107/document.adoc
      - iso-10303-515/document.adoc
      - iso-10303-43/document.adoc
      - iso-10303-56/document.adoc
      - iso-10303-59/document.adoc
      - iso-10303-46/document.adoc
      - iso-10303-53/document.adoc
      - iso-10303-504/document.adoc
      - iso-10303-47/document.adoc
      - iso-10303-105/document.adoc
      - iso-10303-517/document.adoc
      - iso-10303-523/document.adoc
      - iso-10303-42/document.adoc
      - iso-10303-42/document.adoc
      - iso-10303-42/document.adoc
      - iso-10303-42/document.adoc
      - iso-10303-62/document.adoc
      - iso-10303-506/document.adoc
      - iso-10303-57/document.adoc
      - iso-10303-54/document.adoc
      - ...
```

Notice that `      - iso-10303-42/document.adoc` occurs 4 times.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.27.
Duplicated entries removed.
In the folder `iso-10303-stepmod-wg12\data\resource_docs\geometric_and_topological_representation\` there are 4 files with mask `*resource.xml`:
- Copy of resource.xml
- origresource.xml
- resource.xml
- v2resource.xml

The mask updated to the `resource.xml` and `module.xml` strictly.


Sorting added:
```
---
metanorma:
  source:
    files:
      - iso-10303-41/document.adoc
      - iso-10303-42/document.adoc
      - iso-10303-43/document.adoc
      - iso-10303-44/document.adoc
      - iso-10303-45/document.adoc
      - iso-10303-46/document.adoc
      - iso-10303-47/document.adoc
      - iso-10303-51/document.adoc
      - iso-10303-53/document.adoc
      - iso-10303-54/document.adoc
      - iso-10303-56/document.adoc
      - iso-10303-57/document.adoc
      - iso-10303-58/document.adoc
      - iso-10303-59/document.adoc
      - iso-10303-61/document.adoc
      - iso-10303-101/document.adoc
      - iso-10303-105/document.adoc
      - iso-10303-107/document.adoc
      - iso-10303-403/document.adoc
      - iso-10303-409/document.adoc
      - iso-10303-410/document.adoc
      - iso-10303-421/document.adoc
      - iso-10303-433/document.adoc
      - iso-10303-436/document.adoc
      - iso-10303-439/document.adoc
      - iso-10303-442/document.adoc
      - iso-10303-443/document.adoc
      - iso-10303-503/document.adoc
      - iso-10303-504/document.adoc
      - iso-10303-506/document.adoc
      - iso-10303-517/document.adoc
      - iso-10303-518/document.adoc
      - iso-10303-520/document.adoc
      - iso-10303-521/document.adoc
      - iso-10303-522/document.adoc
      - iso-10303-523/document.adoc
      - iso-10303-1001/document.adoc
...
      - iso-10303-1821/document.adoc
      - iso-10303-1822/document.adoc
      - iso-10303-1823/document.adoc
      - iso-10303-1824/document.adoc

  collection:
    organization: "ISO/TC 184/SC 4/WG 12"
    name: "ISO 10303 in Metanorma"
```
