### ISSUE TITLE
Generated `collection.{sh,yml}` should only contain relative paths

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#113]
Should never have absolute paths.

collection.sh:
```sh
bundle exec metanorma collection collection.yml -x xml,html,presentation -w /Users/me/src/mn/iso-10303-srl/documents/output -c cover.html
```

collection.yml:
```yaml
manifest:
  level: collection
  title: ISO collection
  manifest:
  - level: document
    title: Document
    docref:
    - fileref: /Users/me/src/mn/iso-10303-srl/documents/iso-10303-61/document.xml
      identifier: iso10303-61
      sectionsplit: true
    - fileref: /Users/me/src/mn/iso-10303-srl/documents/iso-10303-41/document.xml
      identifier: iso10303-41
      sectionsplit: true
...
```
