### ISSUE TITLE
Create `express-g-diagrams.yaml` file per document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#115]
So that all EXPRESS-G diagrams are listed:

e.g.
* https://github.com/metanorma/iso-10303-detached-docs/blob/main/documents/iso-10303-104/express-g-diagrams.yaml

e.g.
```yaml
---
- path: ../../../schemas/structural_response_definition_schema/images/fig-d-01.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-02.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-03.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-04.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-05.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-06.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-07.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-08.svg
- path: ../../../schemas/structural_response_representation_schema/images/fig-d-09.svg
```
