### ISSUE TITLE
publication_index.xml processing is missing files when run in iso-10303-srl

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#124]
Following instruction from https://github.com/metanorma/iso-10303-srl/issues/21, I am compiling the following publication_index.xml to generate parts 46, 47, 49, 59, 51:

````
<!DOCTYPE part1000.publication_index SYSTEM "../../dtd/p1000_publication_index.dtd">

<part1000.publication_index 
        name="CR_part42" 
        collector_bug="7876" 
        wg.number.publication_set="10924" 
        wg.number.publication_set_comments="Change request to support AP242 Ed2 IS corrections" 
        date.iso_submission="2022" 
        date.iso_publication="2022"
        sc4.working_group="12">

  <description>
    The modules and/or resources and/or BO/domain Models that are to be added to Part1000 as part of change request CR_part42.
    The STEPmod CVS repository's files should be tagged as: CR_part42
  </description>

        <contacts>
      <projlead ref="wg12convener"/>
      <editor ref="benurick"/>
        </contacts>

    <precedent_changes>
        <change current_id="CR_part42" precedent_id="SMRLv8"/>
    </precedent_changes>

        <resource_docs>
        <resource_doc name="visual_presentation" version="6" wg.number.supersedes="4829" wg.number.express.supersedes="4830" checklist.internal_review="6142" checklist.project_leader="6143" checklist.convener="6144" number="46" wg_number="6140"/>
<resource_doc name="shape_variation_tolerances" version="3" sc4.working_group="12" checklist.internal_review="" checklist.project_leader="" checklist.convener="" number="47" wg_number="7296"/>
<resource_doc name="process_structure_and_properties" version="1" number="49" wg_number="8493"/>
<resource_doc sc4.working_group="12" name="mathematical_constructs" version="1" number="50" wg_number="950"/>
<resource_doc name="mathematical_representation" version="1" wg.number.supersedes="1000" wg.number.express.supersedes="1001" checklist.internal_review="3253" checklist.project_leader="3254" checklist.convener="3255" number="51" wg_number="3250"/>
     </resource_docs>
</part1000.publication_index>
````
as follows:

````
java -Xss5m -jar $STEPMOD2MN iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_TEST_00046-00051/publication_index.xml --output iso-10303-srl/CR_TEST_00046-00051
````

This successfully generates a collection manifest and script, as it did under iso-10303-stepmod. But the collection only includes 46, 47, 51. It is skipping 49 process_structure_and_properties, and 51 mathematical_constructs. That applies to all of iso-10303-srl/CR_TEST_00046-00051, collection.yml, and collection.sh.

Folders for those parts exist as normal under iso-10303-srl/iso-10303-stepmod-wg12/data/resource_docs, and the corresponding part document folders exist in iso-10303-srl/documents . So the omission of 49 and 51 doesn't make sense.

**Comment by opoudjis** [comment]
There were no such omissions in the collection of parts 41-45. I will note other such omissions as I go.

**Comment by opoudjis** [comment]
Omitted parts:

* 49
* 50
* 52

**Comment by opoudjis** [comment]
So of the 50 documents in iso-10303-stepmod that were considered resource documents and that we were not told were obsolete, 22 are being excluded.

I need confirmation that they are all supposed to be excluded. As I already noted, standalone folders for these parts are still being generated.

**Comment by ronaldtse** [comment]
I need to clarify here:

1. There is a document migration process (=> `documents/`). We need to migrate ALL documents. This is IRRELEVANT to whether the documents are valid or invalid or what stage they're in. 
2. There is an index / collection migration process. One index file (`publication_index.xml`) goes into 1 Metanorma collection YAML file (a configuration file). This is IRRELEVANT to what documents are migrated.

These two processes MUST BE FULLY INDEPENDENT.

It seems that they are not in stepmod2mn.

@Intelligent2013 can you please help confirm? Thanks!

**Comment by Intelligent2013** [comment]
@opoudjis if document doesn't exists in the repository index, then `stepmod2mn` skips it. It was made in the ticket https://github.com/metanorma/iso-10303-stepmod/issues/39

> These two processes MUST BE FULLY INDEPENDENT.

@ronaldtse `stepmod2mn` always checks the repository index, and omit the documents that don't include in it. I have to add the optional parameter `--ignore-repository-index` to migrate all documents.

**Comment by ronaldtse** [comment]
> @ronaldtse `stepmod2mn` always checks the repository index, and omit the documents that don't include in it. I have to add the optional parameter `--ignore-repository-index` to migrate all documents. 

@Intelligent2013 let's change this behavior so that it fits my description above that the two processes are independent. 

We should migrate ALL documents at any time. Please make the behavior of `--ignore-repository-index` the default and only one (so we can remove the `--ignore-repository-index` option).

The `publication_index.xml` file is only relevant to generate a Metanorma collection file. It should not be involved in any logic.

Thanks!

**Comment by ronaldtse** [comment]
P.S. The issue described in https://github.com/metanorma/iso-10303-stepmod/issues/39 is valid, but the solution is not what we want. We do not want to "not migrate the documents"; instead, we want to migrate all documents but create a collection that does not compile them.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/stepmod2mn/releases/tag/v1.30.

The command:
```
java -Xss5m -jar $STEPMOD2MN iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_TEST_00046-00051/publication_index.xml --output iso-10303-srl/CR_TEST_00046-00051
```
generates:
- the folder `iso-10303-srl\CR_TEST_00046-00051`:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/845eef98-d748-46af-97e6-4052e42180e5)
- `metanorma.yml`:
```yaml
---
metanorma:
  source:
    files:
      - iso-10303-46/document.adoc
      - iso-10303-47/document.adoc
      - iso-10303-51/document.adoc

  collection:
    organization: "ISO/TC 184/SC 4/WG 12"
    name: "ISO 10303 in Metanorma"
```
- `iso-10303-srl\collection.sh`
```sh
INPUT_REPOS="iso-10303-46 iso-10303-47 iso-10303-51"

for name in $INPUT_REPOS
do
  echo $name
  cd CR_TEST_00046-00051/$name
  sh ./html_attachments.sh
  bundle exec metanorma -x xml document.adoc
  cd  ../..
done
bundle exec metanorma collection collection.yml -x xml,html,presentation -w CR_TEST_00046-00051/output -c cover.html
```

- `iso-10303-srl\collection.yml`
```yaml
...
  manifest:
  - level: document
    title: Document
    docref:
    - fileref: CR_TEST_00046-00051/iso-10303-46/document.xml
      identifier: iso10303-46
      sectionsplit: true
    - fileref: CR_TEST_00046-00051/iso-10303-47/document.xml
      identifier: iso10303-47
      sectionsplit: true
    - fileref: CR_TEST_00046-00051/iso-10303-51/document.xml
      identifier: iso10303-51
      sectionsplit: true
  - level: attachments
    title: Attachments
    docref:
    - fileref: CR_TEST_00046-00051/iso-10303-46/../../schemas/resources/presentation_organization_schema/presentation_organization_schema.exp
      identifier: presentation_organization_schema.exp
      attachment: true
...
    - fileref: CR_TEST_00046-00051/iso-10303-47/../../schemas/resources/shape_aspect_definition_schema/shape_aspect_definition_schema.exp
      identifier: shape_aspect_definition_schema.exp
      attachment: true
...
    - fileref: CR_TEST_00046-00051/iso-10303-51/../../schemas/resources/mathematical_context_schema/mathematical_context_schema.exp
      identifier: mathematical_context_schema.exp
      attachment: true
...
```

- `iso-10303-srl\cover.html`

@ronaldtse @opoudjis please tell me if I did something wrong.

**Comment by opoudjis** [comment]
I'm getting that, alright, @Intelligent2013 , but that is the behaviour we do not want. If INPUT_REPOS="iso-10303-46 iso-10303-47 iso-10303-51"`, that explicitly means that 49 and 50 are still being skipped, and we do not want them skipped, we want them generated in our adhoc collection.

**Comment by ronaldtse** [comment]
@Intelligent2013 for each publication_index.xml file we do not need to generate the documents. Only the Metanorma.yml, collection.yml and shell scripts. The documents should refer back to the main collection generated under “documents”.

**Comment by Intelligent2013** [comment]
ok, then `stepmod2mn` will be updated so:
- 'documents' generation mode:
  - command line `java -Xss5m -jar target/stepmod2mn-1.31.jar iso-10303-srl/iso-10303-stepmod-wg12 --output  iso-10303-srl/documents`
  - without `metanorma.yml`, `collection.yml`, `collection.sh`, `cover.html` generation

- 'publication_index.xml' processing mode:
  - command line `java -Xss5m -jar target/stepmod2mn-1.31.jar iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_TEST_00046-00051/publication_index.xml --output iso-10303-srl/CR_TEST_00046-00051 --documents  iso-10303-srl/documents`
  Note: additional parameter `--documents`
  -  `metanorma.yml`, `collection.yml`, `collection.sh`, `cover.html` generation with relative paths to the folders `documents` and `schemas`.

**Comment by Intelligent2013** [comment]
> I'm getting that, alright, @Intelligent2013 , but that is the behaviour we do not want. If `INPUT_REPOS="iso-10303-46 iso-10303-47 iso-10303-51"`, that explicitly means that 49 and 50 are still being skipped, and we do not want them skipped, we want them generated in our adhoc collection. This behaviour right now is why 22 of the 50 documents are not being output.

@opoudjis I've confused at all.
49 and 50 skipped due the reason `missing in the repository index`:
```
[WARNING] The document 'mathematical_constructs' skipped in the metanorma collection - it's missing in the repository index.
[WARNING] The document 'process_structure_and_properties' skipped in the metanorma collection - it's missing in the repository index.
```

This was made for issue https://github.com/metanorma/iso-10303-stepmod/issues/39. How should I 'Exclude files not in repository_index.xml'? What does mean 'exclude'?

**Comment by opoudjis** [comment]
I'm referring you to @ronaldtse , I don't understand enough about this all to answer it.

**Comment by ronaldtse** [comment]
@Intelligent2013 the "'publication_index.xml' processing mode" does not migrate or touch the documents. It only creates a `collection.yml` file.

> How should I 'Exclude files not in repository_index.xml'? What does mean 'exclude'?

This is a misread of the original intent of the work here.

There are 2 things:
1. The "source repository" which is now "iso-10303-srl".
2. The "publication artifacts" which are determined by the multiple `collection.yml` etc files.

Excluding a document from 2 does not mean removing it from 1.

So "Exclude files not in repository_index.xml" now means to omit the entry from the `collection.yml` file.

Step 1 does not omit anything.

Here's the desired output.

Assume our input file is `CR_TEST_00046-00051.xml`

## `CR_TEST_00046-00051.metanorma.yml`

```yaml
metanorma:
  source:
    files:
      - documents/iso-10303-46/document.adoc
      - documents/iso-10303-47/document.adoc
      - documents/iso-10303-51/document.adoc

  collection:
    organization: "ISO/TC 184/SC 4/WG 12"
    name: "CR_TEST_00046-00051"
```

## `CR_TEST_00046-00051.collection.yml`

```yaml
  manifest:
  - level: document
    title: Document
    docref:
    - fileref: documents/iso-10303-46/document.xml
      identifier: iso10303-46
      sectionsplit: true
    # ...
  - level: attachments
    title: Attachments
    docref:
    - fileref: schemas/resources/presentation_organization_schema/presentation_organization_schema.exp
      identifier: presentation_organization_schema.exp
      attachment: true
    # ...
...
```

## Do not generate these files

* `collection.sh`
* `cover.html`
* `html_attachments.sh`

## Follow up

We will integrate the shell script functionalities inside stepmod-utils.
