### ISSUE TITLE
Update stepmod2mn according to latest best practice

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#162]
https://github.com/metanorma/iso-10303-srl/pull/44

This PR contains the best practices for:
* module documents: `documents/iso-10303-1051`
* resource documents: `documents/iso-10303-54`

**Comment by Intelligent2013** [comment]
> * module documents: `documents/iso-10303-1051`

- add `changes.yaml`:
```
---
schema: geometric_tolerance
change_edition:
- version: '2'
  description: Minor editorial changes.
```

- add `changes_paths.yaml`:
```
---
- changes.yaml
- schemas/modules/geometric_tolerance/mapping.changes.yaml
- schemas/modules/geometric_tolerance/arm.changes.yaml
- schemas/modules/geometric_tolerance/mim.changes.yaml
```

- add `express-g-diagrams-arm.yaml`:
```
---
- path: ../../../schemas/modules/geometric_tolerance/armexpg1.svg
- path: ../../../schemas/modules/geometric_tolerance/armexpg2.svg
- path: ../../../schemas/modules/geometric_tolerance/armexpg3.svg
- path: ../../../schemas/modules/geometric_tolerance/armexpg4.svg
- path: ../../../schemas/modules/geometric_tolerance/armexpg5.svg
```

- add `express-g-diagrams-mim.yaml`:
```
---
- path: ../../../schemas/modules/geometric_tolerance/mimexpg1.svg
```

- add `schemas.yaml`:
```
---
schemas:
  Geometric_tolerance_arm:
    path: ../../schemas/modules/geometric_tolerance/arm.exp
  Geometric_tolerance_mim:
    path: ../../schemas/modules/geometric_tolerance/mim.exp
```



> * resource documents: `documents/iso-10303-54`

no need update `stepmod2mn`.
