### ISSUE TITLE
Generate `collection.yml` for all documents (including part 1xxx)

### ISSUE THREAD

**Issue by kwkwan** [metanorma/stepmod2mn#186]
In order to generate the iso-10303 collection, the YAML file `collection.yml` needs to be generated in all parts.

The `collection.yml` should look like the lines shown below.

```yaml
directives:
  - documents-inline
bibdata:
  title:
    - language: en
      content: "Industrial automation systems and integration -- Product data representation and exchange -- Integrated generic resource: Quality of product shape data"
    - language: fr
      content: "Systèmes d'automatisation industrielle et intégration -- Représentation et échange de données de produits -- Ressources génériques intégrées: Qualité des données de forme du produit"
  type: collection
  docid:
    type: iso
    id: 10303-1064
  edition: 4
  copyright:
    owner:
      name: International Standards Organization
      abbreviation: ISO
    from: 2022
manifest:
  level: collection
  title: ISO Collection
  manifest:
    - level: document
      title: Document
      sectionsplit: true
      docref:
        - fileref: document.adoc
    - level: attachments
      title: Attachments
      docref:
        - fileref: ../../schemas/modules/event/arm.exp
          identifier: arm.exp
          attachment: true
        - fileref: sections/schemadocs/Event_arm.html
          identifier: Event_arm.html
          attachment: true
        - fileref: ../../schemas/modules/event/mim.exp
          identifier: mim.exp
          attachment: true
        - fileref: sections/schemadocs/Event_mim.html
          identifier: Event_mim.html
          attachment: true
```
