### ISSUE TITLE
Change generation of `collection.yml`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#188]
Needed in:
* https://github.com/metanorma/iso-10303-srl/pull/218

<img width="390" alt="Screenshot 2024-05-08 at 5 25 55 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/66685427-caeb-4c5a-b29c-d65e1bc438d6">

**Comment by Intelligent2013** [comment]
Currently, `stepmod2mn`  v1.55 generates so:
```yaml
  manifest:
    - level: document
      title: Document
      docref:
        - fileref: document.xml
          identifier: iso10303-101
          sectionsplit: true
    - level: attachments
      title: Attachments
```
But in the ticket https://github.com/metanorma/stepmod2mn/issues/186, the `collection.yml` instance is:
```yaml
  manifest:
    - level: document
      title: Document
      sectionsplit: true
      docref:
        - fileref: document.adoc
    - level: attachments
      title: Attachments
```

@ronaldtse which option is correct?
