### ISSUE TITLE
Compare resulted adoc with annotated-express repository

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#32]
Source: https://github.com/metanorma/iso-10303-stepmod-annotate/pull/6

To do: compare .adoc converted from resource.xml with the adoc from https://github.com/metanorma/annotated-express/tree/main/data/documents/resources/fundamentals_of_product_description_and_support
And update `stepmod2mn` tool if necessary.

**Comment by Intelligent2013** [comment]
- [ ] `00-introduction.adoc`

stepmod2mn result:
```adoc
Major subdivisions of this part of ISO 10303 are:

* action_schema;

* application_context_schema;

* approval_schema;
...
```
annotated-express repository document:
```adoc
Major subdivisions of this part of ISO 10303 are:

[lutaml_express, schemas, context, leveloffset=+1]
---
{% for schema in context.schemas %}
* {{ schema.id }}{% if forloop.last == true %}.{% else %};{% endif %}
{% endfor %}
---
```
`schemas.yaml`:
```yaml
---
schemas:
  action_schema:
    path: ../../../resources/action_schema/action_schema_annotated.exp
  application_context_schema:
    path: ../../../resources/application_context_schema/application_context_schema_annotated.exp
...
```

To do:
- [ ] generate `schemas.yaml`
- [ ] update adoc generation
