### ISSUE TITLE
Generate collection.yml with attachments

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#33]
Source; https://github.com/metanorma/stepmod2mn/issues/32

Generate `collection.yml`:
```yaml
directives:
  - documents-inline
bibdata:
  title:
    - language: en
      content: "Industrial automation systems and integration -- Product data representation and exchange -- Integrated generic resource: Fundamentals of product description and support"
    - language: fr
      content: "Systèmes d'automatisation industrielle et intégration -- Représentation et échange de données de produits -- Ressources génériques intégrées: Principes de description et de support de produits"
  type: collection
  docid:
    type: iso
    id: 10303-41
  edition: 6
  copyright:
    owner:
      name: International Standards Organization
      abbreviation: ISO
    from: 2019
manifest:
  level: collection
  title: ISO Collection
  manifest:
    - level: document
      title: Document
      docref:
        - fileref: document.xml
          identifier: iso10303-41
          sectionsplit: true
    - level: attachments
      title: Attachments
      docref:
        - fileref: ../../../resources/action_schema/action_schema.exp
          identifier: action_schema.exp
          attachment: true
...
        - fileref: sections/schemadocs/action_schema.htm
          identifier: action_schema.htm
          attachment: true
```
