### ISSUE TITLE
Add folder processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#37]
Source: https://github.com/metanorma/stepmod2mn/issues/25

> We need to have a command that converts all of these into Metanorma AsciiDoc documents.

Currently, `stepmod2mn` converts concrete `resource.xml` or `module.xml` into adoc.

To do:
- [x] if folder pass as input parameter, then find `resource.xml`s and `module.xml`s in the nested folders and convert them into adoc.

- [x] Generate `metanorma.yml` in the root of path:
```
---
metanorma:
  source:
    files:
      - data/documents/resources/fundamentals_of_product_description_and_support/document.adoc

  collection:
    organization: "ISO/TC 184/SC 4/WG 12"
    name: "ISO 10303 in Metanorma"
```
