### ISSUE TITLE
Remove `_annotated` from `schemas.yaml`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#87]
`schemas.yaml` contains the links to the .exp files with suffix `_annotated`:

```
---
schemas:
  action_schema:
    path: ../../../schemas/action_schema/action_schema_annotated.exp
  application_context_schema:
    path: ../../../schemas/application_context_schema/application_context_schema_annotated.exp
...
```

but from https://github.com/metanorma/stepmod-utils/issues/160
> * `stepmod-utils` "Annotated EXPRESS" output (`*_annotated.exp` files => renamed to `*.exp`)

I.e. in `schemas.yaml` the .exp files should be renamed too.
